.\"
.\" Copyright (c) 2016-2023 Jim Warner <james.warner@comcast.net>
.\" Copyright (c) 2019-2024 Craig Small <csmall@dropbear.xyz>
.\" Copyright (c) 2011-2012 Sami Kerola <kerolasa@iki.fi>
.\" Copyright (c) 1999      George Staikos <staikos@0wned.org>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\"
.TH SYSCTL.CONF 5 2024-10-24 "File Formats"
.SH NAME
sysctl.conf \- Kernel configuration parameters
.SH DESCRIPTION
.B sysctl.conf
is a set of configuration files that contain values to be read in and set by
.BR sysctl (8)\.
.PP
This man page describes the configuration files for \fBprocps sysctl\fR.
If you are using
.BR systemd-sysctl (8)
then refer to
.BR sysctl.d (5)
and note that it won't use the file \fI/etc/sysctl.conf\FR.
.SH CONFIGURATION FORMAT
Each line of the files contain a kernel parameter in the format of
.RS
.sp
.nf
.ne 7
token = value
.fi
.RE
.P
Blank lines or lines that start with "#" or ";" are ignored.
.P
If a line begins with a single \-, any attempts to set the value that fail will be
ignored.
.SH FILES
.BR sysctl (8)
when run with the \fB\-\-system\fR option will read files from directories
in the following list in given order:
.P
.TS
Li.
/etc/sysctl.d/\fR*\fP.conf
/run/sysctl.d/\fR*\fP.conf
/usr/local/lib/sysctl.d/\fR*\fP.conf
/usr/lib/sysctl.d/\fR*\fP.conf
/lib/sysctl.d/\fR*\fP.conf
.TE
.P
The file \fI/etc/sysctl.conf\fR is read last. This file is not used by
.BR systemd-sysctl (8)
which means some kernel parameters will not be set depending on the
version of \fBsysctl\fR that is installed.
.SH BUGS
Maximum supported line length of the value is 4096 characters due
to a limitation of \fI/proc\fR entries in Linux kernel.
.SH EXAMPLES
.RS
.sp
.nf
.ne 7
#
#
kernel.domainname = example.com
; this one has a space which will be written to the sysctl!
kernel.modprobe = /sbin/mod probe
.fi
.RE
.PP
.SH SEE ALSO
.BR sysctl.d (5),
.BR sysctl (8),
.BR systemd-sysctl (8).
