.\"
.\" Copyright (c) 2023 Roman Žilka <roman.zilka@gmail.com>
.\" Copyright (c) 2009-2023 Craig Small <csmall@dropbear.xyz>
.\" Copyright (c) 2018-2023 Jim Warner <james.warner@comcast.net>
.\" Copyright (c) 2011-2012 Sami Kerola <kerolasa@iki.fi>
.\" Copyright (c) 2003      Albert Cahalan
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\"
.TH WATCH 1 "2023-07-14" "procps-ng" "User Commands"
.SH NAME
watch \- execute a program periodically, showing output fullscreen
.SH SYNOPSIS
.B watch
[\fIoptions\fR] \fIcommand\fR
.SH DESCRIPTION
.B watch
runs
.I command
repeatedly, displaying its output and errors (the first screenful).  This
allows you to watch the program output change over time.  By default,
\fIcommand\fR is run every 2 seconds and \fBwatch\fR will run until interrupted.
.SH OPTIONS
.TP
\fB\-b\fR, \fB\-\-beep\fR
Beep if
.I command
has a non-zero exit.
.TP
\fB\-c\fR, \fB\-\-color\fR
Interpret ANSI color and style sequences.
.TP
\fB\-C\fR, \fB\-\-no-color\fR
Do not interpret ANSI color and style sequences.
.TP
\fB\-d\fR, \fB\-\-differences\fR[=\fIpermanent\fR]
Highlight the differences between successive updates. If the optional
\fIpermanent\fR argument is specified then
.B watch
will show all changes since the first iteration.
.TP
\fB\-e\fR, \fB\-\-errexit\fR
Freeze updates on
.I command
error, and exit after a key press. The exit code of
.B watch
will be the code
.I command
exits with. If signal
.B n
is the cause of
.I command
termination, the exit code will be
.B n
+ 128.
.TP
\fB\-g\fR, \fB\-\-chgexit\fR
Exit when the output of
.I command
changes.
.TP
\fB\-n\fR, \fB\-\-interval\fR \fIseconds\fR
Specify update interval.
.B watch
will not allow quicker than 0.1 second
interval, in which the smaller values are converted. Both '.' and ',' work
for any locale. The \fBWATCH_INTERVAL\fR environment variable can be used to persistently
set a non-default interval (following the same rules and formatting).
.TP
\fB\-p\fR, \fB\-\-precise\fR
Execute
.I command
.B \-\-interval
seconds after its previous run started, instead of
.B \-\-interval
seconds after its previous run finished. If it's taking longer than
.B \-\-interval
seconds for
.I command
to complete, it is waited for in either case.
.TP
\fB\-q\fR, \fB\-\-equexit\fR <cycles>
Exit when output of
.I command
does not change for the given number of cycles.
.TP
\fB\-r\fR, \fB\-\-no-rerun\fR
Do not run the program on terminal resize, the output of the program will re-appear at the next
regular run time.
.TP
\fB\-t\fR, \fB\-\-no\-title\fR
Turn off the header showing the interval, command, and last start and running time at the top of the display.
.TP
\fB\-w\fR, \fB\-\-no\-wrap\fR
Turn off line wrapping. Long lines will be truncated instead of wrapped to the next line.
.TP
\fB\-x\fR, \fB\-\-exec\fR
Pass
.I command
to an
.BR exec (3)
call instead of
.B sh \-c .
The program will start a bit quicker. Shell features
(environment setup, variable and pathname expansion, etc.) will be unavailable.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Display version information and exit.
.SH "EXIT STATUS"
.TP
.B 0
Success. Does not represent
.I command
exit code.
.TP
.B 1
Errors unrelated to
.I command
operation.
.TP
.B 2
Errors related to
.I command
execution and management (not its exit code).
.TP
.B any (\-\-errexit)
With
.B \-\-errexit
the last exit code of
.I command
is returned.
.SH ENVIRONMENT
The behavior of
.B watch
is affected by the following environment variables.
.TP
.B WATCH_INTERVAL
Update interval, follows the same rules as the
.B \-\-interval
command line option.
.TP
.B COLUMNS
Terminal screen character width. Set to override autodetection.
.TP
.B LINES
Terminal screen character height. Set to override autodetection.
.SH NOTES
POSIX option processing is used (i.e., option processing stops at
the first non\-option argument).  This means that flags after
.I command
don't get interpreted by
.BR watch
itself.

Non-printing characters are stripped from program output.  Use \fBcat -v\fR as
part of the command pipeline if you want to see them.
.SH EXAMPLES
.PP
To watch the contents of a directory change, you could use
.IP
watch \-d ls \-l

.PP
If you have CPUs with a dynamic frequency and want to observe it change, try the
following. The command is passed to the shell, which allows you to make the
pipeline. The quotes are a feature of the shell too.
.IP
watch \-n1 'grep "^cpu MHz" /proc/cpuinfo | sort -nrk4'

.PP
To monitor the up status of your servers, saving a copy of the output of each
run to a file, you may use this. The
.B \-p
makes the command execute every 10 seconds regardless of how long it took to
complete the previous run.
.IP
watch \-n10 \-p \-d '{ date; for i in 10.0.0.31 10.0.0.32 10.0.0.33; do R=OK; ping \-c2 \-W2 "$i" &>/dev/null || R=FAIL; echo "$i: $R"; done } | tee \-a ~/log'

.PP
You can watch for your administrator to install the latest kernel with
.IP
watch uname \-r
.SH BUGS
When the terminal dimensions change, its contents changes are not registered on the next
.I command
run.
.B \-\-chgexit
will not trigger that turn and the counter of
.B \-\-equexit
will not restart even if
.I command
output changes meanwhile.
.B \-\-differences
highlighting is reset.
.SH "REPORTING BUGS"
Please send bug reports to
.UR procps@freelists.org
.UE
