.makecheck:
  stage: build
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
  artifacts:
    paths:
      - test-suite.log
      - testsuite/*.log
      - testsuite/*.sum
  after_script:
    - make clean

debian:
  extends: .makecheck
  image: debian:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq autopoint autoconf automake libtool-bin gettext make pkg-config libncursesw5-dev dejagnu libnuma-dev libsystemd-dev
