'\" t
.\" (The preceding line is a note to broken versions of man to tell
.\" them to pre-process this man page with tbl)
.\" Man page for skill and snice.
.\" Licensed under version 2 of the GNU General Public License.
.\" Written by Albert Cahalan, converted to a man page by
.\" Michael K. Johnson
.\"
.TH SKILL 1 "October 2011" "procps-ng" "User Commands"
.SH NAME
skill, snice \- send a signal or report process status
.SH SYNOPSIS
.B skill
.RI [ signal ]
.RI [ options ]
.I expression
.br
.B snice
.RI [ "new priority" ]
.RI [ options ]
.I expression
.SH DESCRIPTION
These tools are probably obsolete and unportable.  The command syntax
is poorly defined.  Consider using the killall, pkill, and pgrep
commands instead.
.PP
The default signal for skill is TERM.  Use \-l or \-L to list
available signals.  Particularly useful signals include HUP, INT,
KILL, STOP, CONT, and 0.  Alternate signals may be specified in three
ways: \-9 \-SIGKILL \-KILL.
.PP
The default priority for snice is +4.  Priority numbers range from
+20 (slowest) to \-20 (fastest).  Negative priority numbers are
restricted to administrative users.
.SH OPTIONS
.TP
.B \-f
Fast mode.  This option has not been implemented.
.TP
.B \-i
Bnteractive move.
.TP
.B \-l
List all signal names.
.TP
.B \-L
List all signal names in a nice table.
.TP
.B \-n
No action; perform a simulation of events that would occur but do not
actually change the system.
.TP
.B \-v
Verbose; explain what is being done.
.TP
.B \-w
Enable warnings.  This option has not been implemented.
.TP
.B \-V, \-\-verbose
Display version information and exit.
.PD
.SH "PROCESS SELECTION OPTIONS"
Selection criteria can be: terminal, user, pid, command.  The options
below may be used to ensure correct interpretation.
.TP
.B \-t
The next expression is a terminal (tty or pty).
.TP
.B \-u
The next expression is a username.
.TP
.B \-p
The next expression is a process ID number.
.TP
.B \-c
The next expression is a command name.
.PD
.SH SIGNALS
The behavior of signals is explained in
.BR signal (7)
manual page.
.SH EXAMPLES
.TP
.B snice seti crack +7
Slow down seti and crack commands.
.TP
.B skill \-KILL \-v /dev/pts/*
Kill users on PTY devices.
.TP
.B skill \-STOP viro lm davem
Stop three users.
.TP
.B snice \-17 root bash
Give priority to root's shell
.SH "SEE ALSO"
.BR kill (1),
.BR kill (2),
.BR killall (1),
.BR nice (1),
.BR pkill (1),
.BR renice (1),
.BR signal (7)
.SH STANDARDS
No standards apply.
.SH AUTHOR
.UR albert\@users.sf.net
Albert Cahalan
.UE
wrote skill and snice in 1999 as a replacement for a non-free
version.
.SH "REPORTING BUGS"
Please send bug reports to
.UR procps\@freelists.org
.UE
