.TH WATCH 1 "2010 Mar 01" " " "Linux User's Manual"
.SH NAME
watch \- execute a program periodically, showing output fullscreen
.SH SYNOPSIS
.na
.B watch
.RB [ \-bdehvtx ]
.RB [ \-n
.IR seconds ]
.RB [ \-\-beep ]
.RB [ \-\-color ]
.RB [ \-\-differences[=\fIcumulative\fP]]
.RB [ \-\-errexit ]
.RB [ \-\-exec ]
.RB [ \-\-help ]
.RB [ \-\-interval=\fIseconds\fP]
.RB [ \-\-no\-title ]
.RB [ \-\-version ]
.I command
.SH DESCRIPTION
.B watch
runs
.I command
repeatedly, displaying its output and errors (the first screenfull).  This
allows you to
watch the program output change over time.  By default, the program is run
every 2 seconds; use 
.B \-n
or
.B \-\-interval
to specify a different interval.
.PP
The
.B \-d
or
.B \-\-differences
flag will highlight the differences between successive updates.  Using
.B \-\-differences=\fIcumulative\fP
makes highlighting "sticky", presenting a running display of all
positions that have ever changed.  The
.B \-t
or
.B \-\-no\-title
option turns off the header showing the interval, command, and current
time at the top of the display, as well as the following blank line.  The
.I \-b
or
.I \-\-beep
option causes the command to beep if it has a non-zero exit.
.PP
.B watch
will normally run until interrupted. If you want
.B watch
to exit on an error from the program running use the
.I \-e
or
.I \-\-errexit
options, which will cause
.B watch
to exit if the return value from the program is non-zero.
.PP
By default \fBwatch\fR will normally not pass escape characters, however
if you use the \fI\-\-c\fR or \fI\-\-color\fR option, then
\fBwatch\fR will interpret ANSI color sequences for the foreground.

.SH NOTE
Note that
.I command
is given to "sh \-c"
which means that you may need to use extra quoting to get the desired effect.
You can disable this with the
.I -x
or
.I --exec
option, which passes the command to exec(2) instead.
.PP
Note that POSIX option processing is used (i.e., option processing stops at
the first non\-option argument).  This means that flags after
.I command
don't get interpreted by
.BR watch
itself.
.SH EXAMPLES
.PP
To watch for mail, you might do
.IP
watch \-n 60 from
.PP
To watch the contents of a directory change, you could use
.IP
watch \-d ls \-l
.PP
If you're only interested in files owned by user joe, you might use 
.IP
watch \-d 'ls \-l | fgrep joe'
.PP
To see the effects of quoting, try these out
.IP
watch echo $$
.br
watch echo '$$'
.br
watch echo "'"'$$'"'"
.PP
You can watch for your administrator to install the latest kernel with
.IP
watch uname \-r
.PP
(Just kidding.)
.SH BUGS
Upon terminal resize, the screen will not be correctly repainted until the
next scheduled update.  All
.B \-\-differences
highlighting is lost on that update as well.
.PP
Non-printing characters are stripped from program output.  Use "cat -v" as
part of the command pipeline if you want to see them.
.SH AUTHORS
The original
.B watch
was written by Tony Rems <rembo@unisoft.com> in 1991, with mods and
corrections by Francois Pinard.  It was reworked and new features added by
Mike Coleman <mkc@acm.org> in 1999.  The beep, exec, and error handling
features were added by Morty Abzug <morty@frakir.org> in 2008.
