#
# Testsuite for lib/fileutils program
#

set noarg "${topdir}lib/test_fileutils"

set test "without argument"
spawn $noarg
expect_pass "$test" "Hello, World!"

set badfd "${topdir}testsuite/lib.test/fileutils_badfd.sh"
set test "test bad file descriptor"
spawn $badfd
expect_pass "$test" "test_fileutils: write error: Bad file descriptor"

set full "${topdir}testsuite/lib.test/fileutils_full.sh"
set test "test no space left on device"
spawn $full
expect_pass "$test" "test_fileutils: write error: No space left on device"
