.\" Copyright 1996 Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
.\" Copyright 2014 Jaromir Capik <jcapik@redhat.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH READPROCTAB 3 "14 July 2014" "Linux Manpage" "Linux Programmer's Manual"
.SH NAME
readproctab, freeproctab  \- read information for all current processes at once
.SH SYNOPSIS
.B #include <proc/readproc.h>
.sp
.BI "proc_t** readproctab(int " flags ", ... );"
.br
.BI "void freeproctab(proc_t **" p ");"

.SH DESCRIPTION

.B readproctab
reads information on all processes matching the criteria from
.IR flags ,
allocating memory for everything as needed. It returns a
NULL-terminated list of
.I proc_t
pointers. For more information on the arguments of
.BR readproctab ,
see
.BR openproc (3).

.B freeproctab
frees all memory allocated by
.BR readproctab .

The
.I proc_t
structure is defined in
.IR <proc/readproc.h> ,
please look there for a definition of all fields.

.SH "SEE ALSO"
.BR openproc (3),
.BR readproc (3),
.BR /proc/ ,
.BR /usr/include/proc/readproc.h .
.SH "REPORTING BUGS"
Please send bug reports to
.UR procps@freelists.org
.UE
