#
# Dejagnu tests for sysctl (read only) - part of procps
#
set sysctl ${topdir}src/sysctl
set hostname [ exec cat "/proc/sys/kernel/hostname" ]

set test "sysctl with no arguments"
spawn $sysctl
expect_pass "$test" "^\\s+Usage:\\s+\(lt-\)?sysctl \\\[options\\\] \\\[variable\\\[=value\\\] \.\.\.\\\]"

set test "sysctl reading a variable using slash delimiter"
spawn $sysctl kernel/hostname
expect_pass "$test" "kernel.hostname = ${hostname}"

set test "sysctl reading a variable using dot delimiter"
spawn $sysctl kernel.hostname
expect_pass "$test" "kernel.hostname = ${hostname}"

set test "sysctl reading a variable suppress key"
spawn $sysctl -n kernel.hostname
expect_pass "$test" "${hostname}"

set test "sysctl reading a variable suppress value"
spawn $sysctl -N kernel.hostname
expect_pass "$test" "kernel.hostname"

set test "sysctl reading using a path traversal"
spawn $sysctl /../../etc/passwd
expect_pass "$test" "sysctl: Path is not under /proc/sys/: /proc/sys//../../etc/passwd"

if {[exec id -u] == 0} {
    set test "sysctl recursive read with permission errors"
    unsupported "$test (requires non-root user)"
} else {
    set ipv6_dir "/proc/sys/net/ipv6"
    if {![file isdirectory $ipv6_dir]} {
        unsupported "sysctl read: $ipv6_dir does not exist"
    } else {
        set test "sysctl recursive read with permission errors"
        spawn $sysctl net.ipv6
        expect_pass "$test" "sysctl: permission denied on key 'net\\.ipv6\\..+'"
        expect_spawn_retval "$test" 1
    }
}
