#
# Dejagnu testsuite for kill - part of procps
#
set kill ${topdir}kill


set test "kill with no arguments"
spawn $kill
expect_pass "$test" "Usage:\\s+kill pid ...\\s+Send SIGTERM to every process listed.\\r\\s+kill signal pid ...\\s+Send a signal to every process listed.\\r\\s+kill -s signal pid ...\\s+Send a signal to every process listed.\\r\\s+kill -l\\s+List all signal names.\\r\\s+kill -L\\s+List all signal names in a nice table.\\r\\s+kill -l signal\\s+Convert between signal numbers and names."

set test "kill list signal names"
spawn $kill -l
expect_pass "$test" "^\(\[A-Z12\]\\s*\)+$"

set test "kill list signal names in table"
spawn $kill -L
expect_pass "$test" "^\(\\s+\\d+ \[A-Z12\]+\)+\\s*$"

set test "kill convert signal name to number"
spawn  $kill -l HUP
expect_pass "$test" "^1\\s*"

set test "kill convert signal number to name"
spawn  $kill -l 1
expect_pass "$test" "^HUP\\s*"

set test "kill numbered process"
make_testproc
if { [ file isdirectory "/proc/$testproc1_pid" ] && [ file isdirectory "/proc/$testproc2_pid" ] } {
} else {
    perror "Could not start test processes"
}
set foo [ exec $kill -KILL $testproc1_pid $testproc2_pid ]
wait
wait
if { [ file exists "/proc/$testproc1_pid" ] || [ file exists "/proc/$testproc2_pid" ] } {
    fail "$test"
} else {
    pass "$test"
}


